### PR TITLE
add serialization support

### PR DESCRIPTION
**Pull request by snarfed**
Hey @jbn! How have you been? Finally got around to this. Tried to keep it simple, I'm flexible on all the design decisions here, just needed a way to write CAR. Lmk what you think!

### CODE REVIEW

**Comment by jbn** [comment]
i'll look this weekend. new startup, way less sidequest time. 

(also, if you are interested, i'd transfer github/pypi ownership to you. i've seen you around over the years enough to know you're a good steward for projects like this. obv only if you want though)

**Comment by snarfed** [comment]
Hey, thanks, and no worries! I know how it is.

I don't expect a lot more changes, but I'm happy to take the repo and pypi package if you think it needs more maintenance work than you have bandwidth for. Up to you, I'm ok either way!

**Comment by jbn** [comment]
I think transferring to you is the right move. Maintenance or extension,   you'll be a better lead than me on this. LMK your pypi name so I can add you as the collaborator to affect a transfer. (DM on discord fine if you don't want to post it for whatever reason.)

**Comment by snarfed** [comment]
Sure! Sounds good. I'm snarfed on pypi.

If you have the time, I'd love your eyes on this change either way! I'm not overly worried about it, but I expect you've spent more time in CAR land than me.

**Comment by jbn** [comment]
I will!

Heading out now but will take a look and also transfer in AM

**Comment by jbn** [comment]
LGTM. Def will be a nice feature to have!

**Comment by jbn** [comment]
pypi owner invite sent

**Comment by snarfed** [comment]
Thanks man!

**Comment by jbn** [comment]
Thanks for continuing to make bsky cool! 

(Also tried to transfer ownership but couldn't because you had a fork and github didn't think about that edge case. Did send collaborator request then I assume it gets easier?)

**Comment by snarfed** [comment]
Hah, funny. I just deleted my fork, nothing else important there, feel free to retry.

**Pull request merged**
